### ISSUE TITLE
Interface for distributed reductions

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#113]
I'm a bit worried about the interface we currently have for nodal reductions. There are `FIXMEs` in there that suggest that we'll be changing them to include the nodal reductions. At the same time, to write correct code against the current interface, they need to have a rank reduction wrapped around them. This situation is a bit untenable IMO. Suppose we change those functions to do reductions, and code gets written against them that *also* includes reductions. We'll end up double-reducing, which may be OK for max/min, but not for sums, and it's inefficient in either case. I think we ought to make up our mind pretty soon on this, to avoid pain down the road.

Here's what I'd propose as a solution: Rename all the current functions to include a `_loc` suffix. Create a rank-reducing wrapper (cf. #112) that, for now, raises an error if they're used in a distributed-memory setting. This will break all current distributed-memory uses of those functions. This is my favorite solution because we need to look at all the call sites for these functions anyhow to make sure we don't double-reduce. I also like this because I'm convinced we'll want the rank-local values to be accessible.

x-ref: #112 

cc @thomasgibson @matthiasdiener @MTCam @anderson2981

**Comment by inducer** [comment]
Another option would be to keep all "un-decorated" reductions (`norm` and such) rank-local, and make additional `_dist` versions.

**Comment by thomasgibson** [comment]
I think your first suggestion (having `_loc` reductions) is fine, and let all other reductions be distributed. I would prefer that `norm`, `nodal_sum`, etc. always behave distributedly. Furthermore, they should also make sense for serial runs. I.e. if no MPI comm, then just call the relevant `_loc` function.

Does that sound okay?

**Comment by inducer** [comment]
Yep, that sounds great. Thanks for following up!

**Comment by MTCam** [comment]
fwiw, i like it when things behave the same regardless of domain decomposition.

When calling something like `dcoll.nodal_max`, my expectation would be to get the same answer regardless of how many processors or partitions are involved.  

I think needing local-only field extrema or nodal ops are pretty rare at the user level, and agree that the local-only interface should be relegated to `_loc` status.

**Comment by inducer** [comment]
Sounds good. Looks like we've converged on a plan. Let's treat all the non-`_loc` reductions as if they included an allreduce.
