### ISSUE TITLE
WADG mass-matrix inverse: correctness, excessive flop count

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#114]
Missed this when reviewing #74.

https://github.com/inducer/grudge/blob/30db06b0192f961b989c3bbf45c0f310f098cd9e/grudge/op.py#L767-L785

If `Ndof` is the number of DOFs, then the code above uses `Ndof**4` flops per element, when `Ndof**2` would suffice. What should happen here?

* First of all, I'm not sure the implementation is correct. This computes `inv(ref_M) @ ref_M` as the leading term, which is an identity. To be fair, this came from the original implementation:
  https://github.com/inducer/grudge/blob/30db06b0192f961b989c3bbf45c0f310f098cd9e/grudge/symbolic/mappers/__init__.py#L644-L645
* Then, any matrices that *can* be premultiplied, should be premultiplied.
* Last, any einsums involved should at most have one reduction variable. (Our current einsum isn't smart enough to do anything else efficiently.)

cc @thomasgibson

**Comment by alexfikl** [comment]
Hm, how did this ever work if the formula is not right? I remember testing that quite a bit on non-affine elements (for ellipses and such). But, yeah, that leading `inv(M) @ M` really looks like an identity :confused: 

In the paper, this is written as

![Screenshot_20210602_174512](https://user-images.githubusercontent.com/777240/120561630-80675d80-c3ca-11eb-933c-20ac5c638e83.png)

**Comment by inducer** [comment]
Thanks for digging up the formula! I think I can see the identity in that, too. If math is to be believed, matmuls with an identity shouldn't do much other than produce heat... so why not get rid of them. Maybe #115 is all it is. It would sure kill two birds with one stone in terms of this issue. :)
