### ISSUE TITLE
Timestep estimate might be unnecessarily conservative

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#119]
This code:

https://github.com/inducer/grudge/blob/57d90c902b50fa757f7d6436d9834dbec1cfaf72/grudge/models/__init__.py#L56-L59

takes the min of the geometric factors and the min of the non-geometric factors over all groups and then multiplies them. Technically, I think it would suffice to multiply them together (still obtaining a nodal quantity) and then taking the min. Reducing down to per-group quantities and then multiplying and then taking the min would also work. This is a bit hypothetical for now, since most use is single-group, but it might bite us in the future.

I missed this while reviewing #108.

cc @thomasgibson @MTCam

**Comment by thomasgibson** [comment]
I think that's a very fair point. So the non geometric factor will be a single value per element group. Is there a safe way to broadcast the `dt_non_geometric_factor`s, an array of shape `(ngroups,)` and with a `DOFArray` that doesn't mess with the object types?

**Comment by inducer** [comment]
Sure! Something like this ought to work:
```
DOFArray(actx, tuple(
    nongeo_fac * grp_ary
    for nongeo_fac, grp_ary in zip(dt_non_geometric_factors, dof_ary)))
```
(Remember that each sub-array in the `DOFArray` corresponds exactly to a group.)
