### ISSUE TITLE
Eager distributed: support array containers

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#136]
Currently, only object arrays are supported.

https://github.com/inducer/grudge/blob/1c44c4bb0564d01c2fb58642d5923cb88586340c/grudge/trace_pair.py#L266-L379

**Comment by inducer** [comment]
(In a way, a sub-aspect/duplicate of #97)

**Comment by thomasgibson** [comment]
Will take care of this in https://github.com/inducer/grudge/pull/154 as well, just need to read over the distributed bits to write up a clean conversion.
