### ISSUE TITLE
`grudge.geometry.metrics` assumes `actx.permits_inplace_modification` is True (in 1D)

### ISSUE THREAD

**Issue by kaushikcfd** [inducer/grudge#153]
See
https://github.com/inducer/grudge/blob/a9ee93de30aae6981df1a1d31a7cd046eb076896/grudge/geometry/metrics.py#L428-L429

**Comment by inducer** [comment]
I agree with you. The relevant code is only used in 1D (hence the title change). If/when it becomes an issue, it shouldn't be hard to replace.

**Comment by kaushikcfd** [comment]
It is already a partial issue now as we can't run the hello-grudge example using array-contexts that don't support in-place modification.

> it shouldn't be hard to replace.

Could you please fill me on this.

**Comment by inducer** [comment]
> Could you please fill me on this.

For one, we could use a loopy kernel... though that might run into similar issues as https://github.com/illinois-ceesd/mirgecom/pull/468#issuecomment-899736570.

**Comment by thomasgibson** [comment]
> If/when it becomes an issue, it shouldn't be hard to replace.

:wave: :smile: 

I tried to run my entropy stable 1D shock example using lazy and ran into this exact problem. Is the fix straightforward @inducer or do you forsee some additional complications?

**Comment by inducer** [comment]
A simple workaround would be what was done in the connection case: Simply compute the data using numpy and cache it. Kind of like this:

https://github.com/inducer/meshmode/blob/d1366494a988edee7a684c6459e167f6d8cfa546/meshmode/discretization/connection/direct.py#L125-L132
