### ISSUE TITLE
`DiscretizationCollection._base_to_geoderiv_connection` is broken when using overintegration in lazy-mode

### ISSUE THREAD

**Issue by thomasgibson** [inducer/grudge#174]
The relatively recent change for storing affine geometric terms as constants for the pytato array context is broken when using overintegration. The code currently assumes that the `from_discr` is interpolatory, which is just not true when you have terms defined on a quadrature grid.

I have attempted to circumvent this issue in https://github.com/inducer/grudge/pull/172 but I would really like to settle this once and for all.  And by this, I mean actually taking advantage of affineness even when overintegrating. Especially since having working overintegration with lazy evaluation is a high priority right now.

@inducer --- I don't know if I'm being dense here, but I don't see this as a simple 2-line change in the [method](https://github.com/inducer/grudge/blob/2af3528391bf4cb07f5aacf43f7c6afcc18f693a/grudge/discretization.py#L327). The problem is getting `meshmode` to do the right thing by transferring a `DOFArray` defined on a quadrature grid to the appropriate shape for the `geo_deriv_discr`. Is there something we can do in `grudge` to spoon-feed `meshmode` something it can work with?

**Comment by thomasgibson** [comment]
> Don't all geometry derivatives need to be computed on the base discretization and then interpolated to the quadrature grid from there? How is `_base_to_geoderiv_connection` getting a `quad_dd`?

The derivatives are interpolated to the quadrature grid here: https://github.com/inducer/grudge/blob/main/grudge/geometry/metrics.py#L142-L143

The reason `_base_to_geoderiv_connection` is getting a `quad_dd` is in the operator application routines: https://github.com/inducer/grudge/blob/main/grudge/op.py#L427-L429 (and similar places for the weak derivative operator functions). The incoming dof descriptor must be on the quadrature grid when using overintegration (`dd_in`) and for the kernels to be correct, you need to have your geometry terms at each quadrature node (if non-affine).

When using affine, we just need to broadcast a constant value to each quad node.

**Comment by alexfikl** [comment]
> Can you point to code that does that? I don't think the metrics attempt to project to a quadrature grid (but I'm suggesting we teach them how to do that).

From the code @thomasgibson linked in [here](https://github.com/inducer/grudge/blob/2af3528391bf4cb07f5aacf43f7c6afcc18f693a/grudge/geometry/metrics.py#L142-L143)? It seems to remove the quadrature tag, do the derivatives, and then interpolate back, right?
