### ISSUE TITLE
New CI failures

### ISSUE THREAD

**Issue by thomasgibson** [inducer/grudge#202]
I'm not sure what's going on exactly, but ever since https://github.com/inducer/grudge/pull/201 `main` is now failing CI. It's not clear at the moment what went wrong.

**Comment by thomasgibson** [comment]
https://github.com/inducer/grudge/runs/4692614773?check_suite_focus=true

**Comment by alexfikl** [comment]
As #201 doesn't really touch anything in the cases that are now failing, it's problably unrelated.

My best guess would be that `numpy` got updated to `1.22.0` (#201 seems to still be using `1.21.5`) and something changed. Not sure where that would have an effect though..

**Comment by inducer** [comment]
What's the conclusion here? `main` seems OK, but at the same time, I think the failures were real and possibly indicative of some issue...

**Comment by alexfikl** [comment]
> What's the conclusion here? `main` seems OK, but at the same time, I think the failures were real and possibly indicative of some issue...

Yeah, the failure was very reproducible on the CI, so it does seem like it was real, but I haven't been able to reproduce it locally, so not quite sure how to continue.

And the only difference between the one that succeeded and the one that failed seems to be the machine they're running on:
* succeeded: https://github.com/inducer/grudge/runs/4697205805?check_suite_focus=true
* failed (main): https://github.com/inducer/grudge/runs/4692614773?check_suite_focus=true
* failed (194): https://github.com/inducer/grudge/runs/4694038869?check_suite_focus=true

**Comment by thomasgibson** [comment]
I managed to get CI to pass again by forcing Python 3.9x and NumPy 1.21.x in the conda testing environment: https://github.com/inducer/grudge/pull/204#partial-pull-merging

This seems to suggest that there are some changes under the hood in NumPy/python that cause noticeable differences in computed results (hence the CI failures for convergence tests). I'm going to see if it's specifically just NumPy in a moment.

**Comment by thomasgibson** [comment]
Summary of CI issues I have found so far for **Grudge** tests:

- Python 3.10.x and NumPy 1.22 (This is currently `main`): **FAIL** (https://github.com/inducer/grudge/runs/4729485722?check_suite_focus=true#step:3:1005)
- Python 3.9.x and NumPy 1.22: **FAIL** (https://github.com/inducer/grudge/runs/4729567871?check_suite_focus=true#step:3:977)
- Python 3.9.x and NumPy 1.21.x: **PASS** (https://github.com/inducer/grudge/runs/4729947246?check_suite_focus=true#step:3:987)
- Python 3.10.x and NumPy 1.21.x: **PASS** (https://github.com/inducer/grudge/runs/4729947246?check_suite_focus=true#step:3:987)

**Mirgecom** is also having it's own set of CI-related issues: https://github.com/inducer/grudge/runs/4729947505?check_suite_focus=true#step:3:1785. It appears to not be completely deterministic, which is frustrating (see for example this CI log, which **PASSES**: https://github.com/inducer/grudge/runs/4729769817?check_suite_focus=true)

**Comment by alexfikl** [comment]
@thomasgibson Have you tried running some of those multiple times? (Especially the ones that passed)

From the previous runs on `main` that eventually succeeded with numpy 1.22.0, it seems like it's an annoying intermitent error.

**Comment by inducer** [comment]
I'm trying to chase this in a tmate in #205. So far, I've not had great luck getting a CI machine with AVX-512. Maybe that was a holiday-only thing, where there was a lot of unused capacity of fancy new(-ish) machines in Azure.

I'd rather not wholesale deactivate numpy AVX-512... we still won't know the root cause if we do that.

**Comment by inducer** [comment]
Got one.
```
PYOPENCL_TEST=port python test_grudge.py 'test_convergence_advec(meshmode._acf, "disk", [0.1, 0.05], "weak", "central", 4)' 
```
will reproduce the failure.

**Comment by inducer** [comment]
Setting `NPY_DISABLE_CPU_FEATURES` as mentioned by @alexfikl avoids the failure, so it's quite likely that we're looking at a numpy issue here.

**Comment by inducer** [comment]
```
python -c 'import numpy, sys; sys.exit(not numpy.core.test(extra_argv=["-k", "not test_cython"]))'
python -c 'import numpy, sys; sys.exit(not numpy.linalg.test())'
```
pass on the machine I've got, which is a
```
model name      : Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
stepping        : 7
microcode       : 0xffffffff
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt avx512cd avx512bw avx512vl xsaveopt xsavec xsaves md_clear
```

**Comment by inducer** [comment]
```
NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512CD,AVX512_SKX" 
```
suffices on this particular machine.

**Comment by inducer** [comment]
Something pretty weird is going on here:
```
(testing) runner@fv-az206-222:~/work/grudge/grudge/test$ NPY_DISABLE_CPU_FEATURES="AVX512F,AVX512CD,AVX512_SKX" PYOPENCL_TEST=port python test_grudge.py 'test_convergence_advec(meshmode._acf, "disk", [0.1, 0.05, 0.03], "weak", "central", 4)'
h                   | Error                 | Running EOC      
:-------------------|:----------------------|:------------------
0.31044258369676836 | 0.03125099667154715   |                  
0.22222860084613444 | 0.005222869022031573  | 5.351615794811953
0.1720206313650901  | 0.0026328492472195183 | 2.674741123309122

Overall EOC: 4.248183563858907
```

```
(testing) runner@fv-az206-222:~/work/grudge/grudge/test$ PYOPENCL_TEST=port python test_grudge.py 'test_convergence_advec(meshmode._acf, "disk", [0.1, 0.05, 0.03], "weak", "central", 4)'                                                      
h                  | Error                | Running EOC       
:------------------|:---------------------|:-------------------
0.3006140247881788 | 0.020090132892800663 |                   
0.2235929232886717 | 0.006696727781167631 | 3.7115190117296097
0.1719418319058496 | 0.002756729369474212 | 3.379035094927794 

Overall EOC: 3.5584849316611598
Traceback (most recent call last):
  File "/home/runner/work/grudge/grudge/test/test_grudge.py", line 1114, in <module>
    exec(sys.argv[1])
  File "<string>", line 1, in <module>
  File "/home/runner/work/grudge/grudge/test/test_grudge.py", line 823, in test_convergence_advec
    assert eoc_rec.order_estimate() > order
AssertionError
```
* The values of `h` are not the same.
* The errors are *lower* with AVX-512 enabled.

:exploding_head:

**Comment by inducer** [comment]
The meshes have the same number of elements in each case, making it pretty likely that they're actually the same...

**Comment by alexfikl** [comment]
Just looked a bit at this and it doesn't seem like the meshes are the same. 
```
>>> print(np.linalg.norm(mesh.vertices))
>>> # failing
7.368204974713988
>>> # passing
7.376618122290329
```
From what I can tell, the data in `GeometryBuilder` is the same, but when it gets passed to triangle the data in `mesh_info.points` is different between the two cases.

**Comment by inducer** [comment]
Yep, agreed. I was able to reproduce this on my laptop (That may be my first use of AVX-512? :tada:?) The meshes all seem fine, just different. And the parameters appeared to be sufficiently "pre-asymptotic" that gently different meshes seem to matter. I'm about to submit a PR that simply uses finer mesh resolutions, which seems to recover things. IOW, I don't think there was an actual failure here. It just seems that numpy's AVX-512 probing seems to have left the FPU in a gently different state... for whatever reason.
