### ISSUE TITLE
Random CI failures: downstream mirgecom testing

### ISSUE THREAD

**Issue by thomasgibson** [inducer/grudge#211]
I've noticed that grudge's CI will sporadically fail when running downstream mirgecom tests. Here is an [example](https://github.com/inducer/grudge/runs/4798352500?check_suite_focus=true#step:3:896) log file. What makes this strange is that it is not consistent and grudge will often pass CI without any issues. #210's commit history shows examples of commits where CI will bounce between pass, fail, and pass again. The commits in question did _not_ have the capacity to affect numerical computations/tests.

This one is tricky to reproduce (as in I'm unable to... 😬). The log seems to indicate a test node being taken down somehow, but I'm not quite sure what might be causing that... Logging this issue here for reference.

**Comment by inducer** [comment]
Closing provisionally based on #212.
