### ISSUE TITLE
Inflated geometric factors storage for affine elements

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#314]
In https://github.com/inducer/grudge/pull/310#discussion_r1290338756, @kaushikcfd says:

> I noticed a subtle and sub-optimal behavior that is worth noting. If we are using PyOpenCLActx as a setup actx and PytatoActx as an operational actx, then the frozen geometric factors (such as normals) would be stored at per-DOF even for affine geometry mappings. Such use-cases will bump memory footprint.

If true, this wouldn't just increase memory footprint, but also memory bandwidth requirements.

cc @majosm @matthiasdiener

**Comment by majosm** [comment]
I'm told that we don't use a separate array context for init anymore in Y3, so it looks like this isn't affecting us at the moment.

**Comment by inducer** [comment]
@kaushikcfd Could you elaborate on the circumstance under which you've observed this? Do you happen to know why this happens?

**Comment by kaushikcfd** [comment]
I did not observe this in any production-related drivers. But I was writing some tests for #310 and noticed this behavior and thought sharing would be essential so that others do not repeat the same mistake.

I have attached a minimal reproducer script for posterity.

```python
import grudge
import pyopencl as cl
from meshmode.discretization.connection import FACE_RESTR_INTERIOR

from grudge.array_context import get_reasonable_array_context_class
from meshmode.mesh.generation import generate_regular_rect_mesh

ctx = cl.create_some_context()
cq = cl.CommandQueue(ctx)

ref_actx = get_reasonable_array_context_class(lazy=False, distributed=False)(cq)
actx = get_reasonable_array_context_class(lazy=True, distributed=False)(cq)

mesh = generate_regular_rect_mesh(a=(-0.5, -0.5),
                                  b=(0.5, 0.5),
                                  nelements_per_axis=(16, 16))

dcoll = grudge.make_discretization_collection(ref_actx, mesh, order=4)
nx, ny = actx.thaw(dcoll.normal(FACE_RESTR_INTERIOR))

assert nx[0].shape[-1] == 1  # fails
```

**Comment by inducer** [comment]
Thanks for providing the reproducer. AFAICT, this affects *only* the normals. The main issue is that here:

https://github.com/inducer/grudge/blob/0d501c0c31ad3c5ba8ec55435f1b73168d3707b0/grudge/discretization.py#L770

the setup actx is unconditionally used to populate the normal cache, making this an interface bug more than a "bug bug". Perhaps the most reasonable response is to deprecate `DiscretizationCollection.normal`. `grudge.geometry.normal` takes an actx and does not have this issue (and it's more convenient to use because there's no freeze/thaw cycle needed).

**Comment by inducer** [comment]
#315
