### ISSUE TITLE
Overintegration may not round-trip correctly

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#327]
I.e. upsampling and projecting back gives a different answer.

- [ ] Add a test that it does round-trip correctly

This came up during CEESD Dev today. The claim was said to be made by @tulioricci. @tulioricci, if you have any context to add on the situation in which it came up, please chime in.

cc @MTCam @lukeolson

**Comment by tulioricci** [comment]
When adding tests to mirge-com using overintegration, several were failing.

Poking into it, I added a new test where I prescribe linear profiles (1.0 + 0.1x) for the variables and try to recover the exact gradient of 0.1 (see https://github.com/illinois-ceesd/mirgecom/pull/960/files#diff-0b5345d59d8472426fd9aee0f32f1599e41622b28609b2808425a8e9b63eea03R1086). In this case, even order 1 should give the exact answer. That is the case without over-integration. However, when using over-integration, order 1 would not return the correct gradient. This is shown in the figures below.

![t](https://github.com/inducer/grudge/assets/72670026/63ef8ca8-36ab-4eed-b799-ce2cace998d1)
![t_over](https://github.com/inducer/grudge/assets/72670026/9c901319-adf5-4cd4-b29a-464faf46ba8b)

**Comment by inducer** [comment]
In #329, I'm adding a test that overintegration achieves the same accuracy as standard DG, which seems inconsistent with what you're observing. Closing here, I suspect this may be a mirgecom-only problem.

**Comment by tulioricci** [comment]
Thanks for looking into this! I will think of some additional checks to conduct in mirge-com then.
