### ISSUE TITLE
gmsh-generated unstructured hexahedral mesh fails Gauss's Law test

### ISSUE THREAD

**Issue by MTCam** [inducer/grudge#339]
The attached simple mesh was created in gmsh by splitting tets into hexs.  It has multiple volumes.  It fails the [Gauss's Law test](https://github.com/inducer/grudge/blob/c2be52350a0fc3a6d1c6d3a6972fb374ff23dbd2/test/test_grudge.py#L433) in grudge, and fails to hold a quiescent fluid state in mirgecom, even with inviscid operators.  

[so_weird.msh.txt](https://github.com/inducer/grudge/files/15350392/so_weird.msh.txt)

<img width="629" alt="Screenshot 2024-05-17 at 8 55 45 AM" src="https://github.com/inducer/grudge/assets/8116930/3cba7bdd-23de-4091-9d4e-298934016f91">

```
>       assert abs(int_1 - int_2) < 1e-13
E       assert cl.TaggableCLArray(1.38647505e-09) < 1e-13
E        +  where cl.TaggableCLArray(1.38647505e-09) = abs((cl.TaggableCLArray(0.00285925) - cl.TaggableCLArray(0.00285925)))
```

The only weird thing I can find about this mesh is that its faces aren't exactly coplanar.   The worst face I found was basically a tet with a volume of about -1e-11.

**Comment by inducer** [comment]
As discussed during meeting: I think this may be explained by not accurately integrating the mapping Jacobians (and other geometric factors). If increasing the quadrature order gets this to be accurate, then IMO there's nothing to see here. (But please do this experiment and follow up.)

**Comment by MTCam** [comment]
> As discussed during meeting: I think this may be explained by not accurately integrating the mapping Jacobians (and other geometric factors). If increasing the quadrature order gets this to be accurate, then IMO there's nothing to see here. (But please do this experiment and follow up.)

FYI, the ACTII mesh that MikeA showed in the meeting _does_ pass the Gauss's Law test.  😮

**Comment by MTCam** [comment]
Here's another, simpler mesh that reproduces the Gauss's Law test failure.   Overintegration did not appear to have an affect on the results for any of the hex meshes.  Setting ($p=3$) actually gets a passing test.

Here's the hex version that fails the test for ($p<3$):
[simple_hexs.msh.txt](https://github.com/inducer/grudge/files/15392155/simple_hexs.msh.txt)

Here's the tet version that the hex mesh was generated from:
[simple_tets.msh.txt](https://github.com/inducer/grudge/files/15392144/simple_tets.msh.txt)
