### ISSUE TITLE
Support more vector norms?

### ISSUE THREAD

**Issue by nkoskelo** [inducer/grudge#357]
Currently, the operator,`grudge.op.norm = grudge.reductions.norm` is specified as returning "the vector norm of a function represented by its vector of degrees of freedom." However, only the _2-norm_ and the _infinity_ norms are supported. Should we generalize the function to support all integral "p-norms"?

**Comment by inducer** [comment]
I don't see the need. The 1-norm is the only other mainstream norm that's missing/would be practically relevant, but its integrand is non-smooth at the zero crossings , so we cannot accurately approximate it. I don't foresee anyone urgently needing a 4-norm.
