### ISSUE TITLE
QTAG_XXX is misnamed

### ISSUE THREAD

**Issue by inducer** [inducer/grudge#79]
With the introduction of `QTAG_MODAL` in #77, it's apparent that the `QTAG_` prefixes (for "quadrature tag") are misnamed. "Modal" just isn't a form of quadrature, unless you twist your head in a very special way. "Discretization tag" would make sense, but the `DTAG_` is taken ("domain tag"). `DISCR_TAG_XXX`?

cc @thomasgibson @majosm @alexfikl

**Comment by majosm** [comment]
Would something like `STAG_` (“space tag”) make sense?

**Comment by thomasgibson** [comment]
`DISCR_TAG` is growing on me.

**Comment by alexfikl** [comment]
I always assumed that `QTAG_NONE` was supposed to be the only one of its kind, as other quadrature tags get named by the user, so definitely agree that it's weird.

I'm also on board with `DISCR_TAG_QUAD` and `DISCR_TAG_MODAL` (if I understood @thomasgibson correctly?).

**Comment by thomasgibson** [comment]
What about `DISCR_TAG_BASE` (for basic discretizations, with explicitly defined bases; not quadrature grids) and `DISCR_TAG_MODAL` for modal discretizations? Right now, quadrature discretizations are basically treated as "anything other than those", as shown [here](https://github.com/inducer/grudge/blob/main/grudge/dof_desc.py#L198-L204).

@alexfikl Do we want to take this opportunity to drop in a special `DISCR_TAG_QUAD` specifically for quadrature discretizations? At the moment, Mirgecom uses strings to denote the quadrature grid (like `"quad"`), but it's not widely used at the moment, so we have a window of opportunity before breaking tons of compatibility. @majosm What do you think?

**Comment by alexfikl** [comment]
> What about DISCR_TAG_BASE (for basic discretizations, with explicitly defined bases; not quadrature grids) and DISCR_TAG_MODAL for modal discretizations? Right now, quadrature discretizations are basically treated as "anything other than those", as shown here.

Yeah, that sounds good!

> Do we want to take this opportunity to drop in a special DISCR_TAG_QUAD specifically for quadrature discretizations?

How would that work if there are multiple quadrature discretizations? I'm mostly thinking of [surface PDEs](https://homepages.warwick.ac.uk/staff/C.M.Elliott/DziEll13a.pdf) here, where there are all sorts of nasty nonlinear terms that you could treat differently.

**Comment by thomasgibson** [comment]
> How would that work if there are multiple quadrature discretizations? I'm mostly thinking of [surface PDEs](https://homepages.warwick.ac.uk/staff/C.M.Elliott/DziEll13a.pdf) here, where there are all sorts of nasty nonlinear terms that you could treat differently.

That's a good question. I guess that's why `str` are acceptable input (for basically letting the user decide what to do with it). Alternatively, we could make `DISCR_TAG_QUAD` take additional parameters (for example, a `domain_tag`?) Sort of like how `DTAG_BOUNDARY` can take a tag to help specialize for specific types of boundaries.

**Comment by alexfikl** [comment]
> That's a good question. I guess that's why `str` are acceptable input (for basically letting the user decide what to do with it). Alternatively, we could make `DISCR_TAG_QUAD` take additional parameters (for example, a `domain_tag`?) Sort of like how `DTAG_BOUNDARY` can take a tag to help specialize for specific types of boundaries.

Or just let the user inherit from `DISCR_TAG_QUAD` for problem specific stuff? That doesn't sound too bad.

**Comment by inducer** [comment]
I don't know how realistic it is, but the intent of user-defined quadrature tags was to define multiple "levels" of overintegration. I don't know if anyone would really want that, but it seemed easy to do. Maybe that's worth keeping. I like the proposal of making user-defined tags by inheriting rather than by strings.

**Comment by inducer** [comment]
I also think `DISCR_TAG_xxx` is OK.
