### ISSUE TITLE
Teach grudge about array containers

### ISSUE THREAD

**Issue by MTCam** [inducer/grudge#97]
[There is a work around for this](https://github.com/illinois-ceesd/mirgecom/blob/d012fbaca0f1c2b0c71c59a200d946fc0c04d9fd/mirgecom/euler.py#L154), but currently this happens when calling `cross_rank_trace_pairs` with a `mirgecom.fluid.ConservedVars` array container.

```
  File "/Users/mtcampbe/CEESD/devel/emirge/grudge/grudge/op.py", line 554, in cross_rank_trace_pairs
    return _cross_rank_trace_pairs_scalar_field(dcoll, ary, tag=tag)
  File "/Users/mtcampbe/CEESD/devel/emirge/grudge/grudge/op.py", line 505, in _cross_rank_trace_pairs_scalar_field
    rbcomms = [_RankBoundaryCommunication(dcoll, remote_rank, vec, tag=tag)
  File "/Users/mtcampbe/CEESD/devel/emirge/grudge/grudge/op.py", line 505, in <listcomp>
    rbcomms = [_RankBoundaryCommunication(dcoll, remote_rank, vec, tag=tag)
  File "/Users/mtcampbe/CEESD/devel/emirge/grudge/grudge/op.py", line 472, in __init__
    local_data = self.array_context.to_numpy(flatten(self.local_dof_array))
  File "/Users/mtcampbe/CEESD/devel/emirge/arraycontext/arraycontext/impl/pyopencl.py", line 292, in to_numpy
    return array.get(queue=self.queue)
AttributeError: 'ConservedVars' object has no attribute 'get'
```

**Comment by inducer** [comment]
Thanks for the report! Ultimately, this will need to take the form of container support in `cross_rank_trace_pairs`.

**Comment by inducer** [comment]
What's missing?

- `cross_rank_trace_pairs`, as originally reported by @MTCam 
- the mass operators
- `op.norm` (perhaps generally the reductions?)
- There are a big bunch of `norm(... .join())`s e.g. [here](https://github.com/illinois-ceesd/mirgecom/blob/eaa9e6cdf82e65a7d90855a4cfe72dc8192acc1a/test/test_euler.py) that could then be deleted.

**Comment by MTCam** [comment]
Is this still necessary? 

```python
    # [Bassi_1997]_ eqn 15 (s = grad_q)    
    grad_cv = make_conserved(dim, q=dg_grad(discr, cv.join(), cv_flux_bnd.join()))
```

`dg_grad` calls `weak_local_grad(discr, cv.join(), nested=False)`.

**Comment by inducer** [comment]
I think so, for now. I'll add it to the list.

**Comment by inducer** [comment]
Turns out that this is also an (eager) performance issue, as it'll help avoid the (avoidable, moderately expensive) use of `ndindex` [here](https://github.com/inducer/pytools/blob/24f60aa04aa27cacf134b9b8434e24854aec67f4/pytools/obj_array.py#L138-L139) in favor of [this code](https://github.com/inducer/arraycontext/blob/77b03e5e9eed69a9cfd51bebae68e0f746c5bacf/arraycontext/container/__init__.py#L175-L184), which has a "fast path" for the simpler, common cases.
